### ISSUE TITLE
Comment "stimulusFetch: 'lazy'" is dropped from Stimulus Controller

### ISSUE THREAD

**Issue by Kocal** [sensiolabs/minify-bundle#10] opened 2024-10-24 06:11 UTC
Hey :)

Given my Stimulus controller:
```js
import { redo as commandRedo, undo as commandUndo } from "@codemirror/commands";
import { markdown } from "@codemirror/lang-markdown";
import { Compartment, EditorSelection } from "@codemirror/state";
import { githubDark } from "@fsegurai/codemirror-theme-github-dark";
import { githubLight } from "@fsegurai/codemirror-theme-github-light";
import { Controller } from "@hotwired/stimulus";
import { EditorView, basicSetup } from "codemirror";
import { codeLanguages } from "../codemirror/code_languages.js";
import { lightDarkThemeSwitcher } from "../codemirror/light_dark_theme_switcher.js";

/* stimulusFetch: 'lazy' */
export default class extends Controller {
    static targets = ["textarea"];
    static classes = ["editor"];

    /* ... */
}
```

After being minified, the comment `/* stimulusFetch: 'lazy' */` disappear from the source code:
<img width="937" alt="image" src="https://github.com/user-attachments/assets/513f2ab0-d61a-48d3-889a-2a6a19283c73">

Which load the controller (even if not needed since there are no `data-controller="markdown-editor"` on the page) and load all the dependencies (a lot): 
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/b8291122-55e0-4b11-aebc-1410fa785db5">

**Comment by Kocal** [comment] 2024-10-24 06:20
I've tried to add a `!` to the comment, like this: `/*! stimulusFetch: 'lazy' */`, it's usually something that tell minifiers to NOT remove the comment, thus, Minify supports that behavior for CSS (https://github.com/tdewolff/minify#css) but for JS I don't know.

Anyway, if I use the new comment like that:
```js
import { redo as commandRedo, undo as commandUndo } from "@codemirror/commands";
import { markdown } from "@codemirror/lang-markdown";
import { Compartment, EditorSelection } from "@codemirror/state";
import { githubDark } from "@fsegurai/codemirror-theme-github-dark";
import { githubLight } from "@fsegurai/codemirror-theme-github-light";
import { Controller } from "@hotwired/stimulus";
import { EditorView, basicSetup } from "codemirror";
import { codeLanguages } from "../codemirror/code_languages.js";
import { lightDarkThemeSwitcher } from "../codemirror/light_dark_theme_switcher.js";

/*! stimulusFetch: 'lazy' */
export default class extends Controller {
    static targets = ["textarea"];
    static classes = ["editor"];
```

Then I see the comment being at the very top of the file: 
<img width="678" alt="image" src="https://github.com/user-attachments/assets/2f49604c-b8a5-496c-a62b-257932532dab">

And the lazy-loading behavior still not works.

**Comment by smnandre** [comment] 2024-10-25 17:42
Is it happening both for asset-map:compile and Minify:asset command or just the later?

**Comment by MatTheCat** [comment] 2024-10-25 20:22
See https://github.com/tdewolff/minify/issues/552

**Comment by MatTheCat** [comment] 2024-10-26 09:03
Okay dug a little bit deeper and minify will only keep a comment if
- it is in top of the file
- it is “important”, meaning it starts with `/*!`

So we could make this work by putting `/*! stimulusFetch: 'lazy' */` on top of lazy controllers, and updating [the StimulusBundle’s regexp](https://github.com/symfony/stimulus-bundle/blob/60ec83e56c94d441eae0c33d858addf6f1c780dd/src/AssetMapper/ControllersMapGenerator.php#L81) so that it allows the exclamation mark…

**Comment by MatTheCat** [comment] 2024-10-26 09:13
Just thought of something simpler :sweat_smile: 

StimulusBundle’s `ControllersMapGenerator` checks for the comment in the compiled asset if it exists: https://github.com/symfony/stimulus-bundle/blob/60ec83e56c94d441eae0c33d858addf6f1c780dd/src/AssetMapper/ControllersMapGenerator.php#L80

Always checking against the **source** file content would solve this issue:

```diff
- $content = $asset->content ?: file_get_contents($asset->sourcePath);
+ $content = file_get_contents($asset->sourcePath);
```

**Comment by smnandre** [comment] 2024-10-26 12:54
Are you sure this does not work with AssetMapper ? When i tested it i’m pretty sure it did, but i may had another implémentation at that point

**Comment by smnandre** [comment] 2024-10-26 12:55
(i’m 100km from my computer right now ^^)

**Comment by MatTheCat** [comment] 2024-10-26 13:03
Yes I successfully reproduced what @Kocal reported: given the following controller:

```js
import { Controller } from '@hotwired/stimulus';

/* stimulusFetch: 'lazy' */
export default class extends Controller {
    connect() {
        this.element.textContent = 'Hello Stimulus! Edit me in assets/controllers/hello_controller.js';
    }
}
```

The `ControllersMapGenerator` gets the following to search `/* stimulusFetch: 'lazy' */` in:

```js
import{Controller}from"@hotwired/stimulus";export default class extends Controller{connect(){this.element.textContent="Hello Stimulus! Edit me in assets/controllers/hello_controller.js"}}
```

It doesn’t find the comment and thus considers the controller to be loaded eagerly.

**Comment by smnandre** [comment] 2024-10-29 17:33
https://github.com/symfony/ux/pull/2304 will be released in the incoming weeks, so not sure if we can do something in the meantime here :|

**Closed** 2024-10-31 11:46 UTC

**Comment by smnandre** [comment] 2024-11-30 18:42
symfony/stimulus-bundle 2.2.22 has been released, with the fix from @MatTheCat 

To me everything works as expected (had a weird cache first but not sure if related)

Could you guys check on your side?

**Comment by Kocal** [comment] 2024-12-01 09:24
I will check :)

**Comment by MatTheCat** [comment] 2024-12-01 15:55
I won’t be able to help since we use the WebpackEncoreBundle :confused:

**Comment by Kocal** [comment] 2024-12-01 21:20
... weeeell, after a whole day of VM/server issues (just after deploying the commit to use this bundle on my website.... 🧐 (just a coincidence)).

IDK if I did something wrong, but:
- go to https://hugo.alliau.me/cv, 
- open your DevTools at Network tab 
- disable Cache and use 3G throttle
- you can see https://hugo.alliau.me/assets/controllers/places_controller-4BdSRAq.js and https://hugo.alliau.me/assets/controllers/markdown_editor_controller-tbJ1hWZ.js controllers are loaded, even if not present on the page.

I believe this is an issue from AssetMapper and automatic usages of `<link rel="modulepreload">`, since you see the request initiator is the page itself and not Stimulus:
<img width="847" alt="image" src="https://github.com/user-attachments/assets/5549e971-da02-4927-bb57-cb3b754706ef">

**Comment by MatTheCat** [comment] 2024-12-02 07:38
Tried StimulusBundle 2.22 on a small project and it behaves as expected: controller is loaded when not being lazy or being used on the page.

@Kocal `modulepreload` probably means you have some JS files requiring your `places` and `markdown-editor` controllers?

**Comment by Kocal** [comment] 2024-12-04 16:01
I'm stupid 🤦🏻 

When upgrading Symfony UX packages, I ran `symfony composer update 'symfony/ux-*'`, which... does not involve `symfony/stimulus-bundle`. I was still using StimulusBundle 2.21 🫠  

Updated StimulusBundle to 2.22, it's working now!
